### ISSUE TITLE
Install doc

### ISSUE THREAD

**Issue by MikeyBeez** [xlang-ai/OpenAgents#21]
Will you be creating a dedicated installation document that includes testing and troubleshooting?

**Comment by BlankCheng** [comment]
Hi, thanks for your suggestion! Currently, we have installation documentation in `backend/README.md` and `frontend/README.md`. 
Do you recommend some examples or templates so that we can make the guiding procedure better, especially about the testing and troubleshooting? Or you can make a PR about it if you would like to~
