### ISSUE TITLE
Local deploy.... every chat reponse slow 

### ISSUE THREAD

**Issue by hugenshen** [xlang-ai/OpenAgents#41]
amazing product!!!
I have deploy the code in local, but i find  a problem that  every chat  reponse so slow...
i see the log always show the msg :
75%|███████▌  | 12/16 [00:04<00:00,  4.19it/s]OpenAgents-main\real_agents\plugins_agent\plugins\DreamInterpreter\openapi.yaml and DreamInterpreter/paths/__init__.py do not match. Load the later.
how can i  fix it ?    how can i join the discord group?  thanks

**Comment by BlankCheng** [comment]
Hi, the discord link is here https://discord.com/invite/4Gnw7eTEZR, welcome to join the discussion.
Regarding the deploy issue, it seems it is stuck at the flask start phase. Can it generate a response slowly, or just no response? For the former case, it might be due to LLM API issue. For the latter one, we shall investigate further.

**Comment by likeucode** [comment]
I have the same problem, do you have figure it out?

**Comment by BlankCheng** [comment]
Please check the #99. Closed as inactive. Feel free to reopen it if you meet any problems.
