### ISSUE TITLE
sample plugin agent problem

### ISSUE THREAD

**Issue by harrywang** [xlang-ai/OpenAgents#66]
I am trying the sample plugin agent and had the following result:

<img width="2219" alt="Screenshot 2023-11-03 at 1 51 19 PM" src="https://github.com/xlang-ai/OpenAgents/assets/595772/73c63ef0-dfd9-41f3-aa5b-738ff22a2d08">

the plugins are not triggered and no results were shown - any idea on what happened?

Thanks.

**Comment by Timothyxxx** [comment]
Oh, that's the problem caused by the less powerful foundation language model, in short, you can try to switch from `gpt-3.5-turbo-16k` to `gpt-4` to see whether it works.

The long story is that only a tiny set of LLMs (a.k.a GPT-4) can be used to do tool use, planning, and reasoning, through instruction prompting. And for all the frameworks you can see today, and fancy demos they made, they all rely on the same assumption that the foundation and the source power of the system that, LLM is very strong, strong enough to take their prompting seriously, make plans, self-correct and response with very little factual problems. Dating back to 2021 when we were still studying the gpt3 and codex (the ancestor, or to say, the prototype of ChatGPT and GPT-4), these models cannot suffer from more than 2 instructions, the same for today's models.

**Comment by Timothyxxx** [comment]
There are actually other ways to make it better, instead of prompting, check our tech report [here](https://arxiv.org/pdf/2310.10634.pdf).

**Comment by harrywang** [comment]
> Oh, that's the problem caused by the less powerful foundation language model, in short, you can try to switch from `gpt-3.5-turbo-16k` to `gpt-4` to see whether it works.
> 
> The long story is that only a tiny set of LLMs (a.k.a GPT-4) can be used to do tool use, planning, and reasoning, through instruction prompting. And for all the frameworks you can see today, and fancy demos they made, they all rely on the same assumption that the foundation and the source power of the system that, LLM is very strong, strong enough to take their prompting seriously, make plans, self-correct and response with very little factual problems. Dating back to 2021 when we were still studying the gpt3 and codex (the ancestor, or to say, the prototype of ChatGPT and GPT-4), these models cannot suffer from more than 2 instructions, today models are getting better, but still a long way to go as the general world imagined.

@Timothyxxx thanks a lot for the information - this is very helpful.
