### ISSUE TITLE
xlang-code-interpreter repo link missing

### ISSUE THREAD

**Issue by harrywang** [xlang-ai/OpenAgents#72]
I am reading the doc at https://github.com/xlang-ai/OpenAgents/blob/main/backend/README.md#------------5-others-optional--------

and found that the link to [code-interpreter-docker](https://github.com/xlang-ai/xlang-code-interpreter)) repository is broken - is that repo available?

Thanks.

**Comment by BlankCheng** [comment]
No, it's not a repo now, thanks for pointing out the deprecated link. Only the docker is uploaded now~

**Comment by harrywang** [comment]
> No, it's not a repo now, thanks for pointing out the deprecated link. Only the docker is uploaded now~

will this be opensourced soon？

**Comment by BlankCheng** [comment]
Maybe not in our plan now unless it is a major request because it is not relevant to the main logic of this project and bit tedious. 
However, if you are interested in the implementation, we are willing to share any details and answer any questions! We can discuss it here or on discord.

**Comment by RaoulDrake** [comment]
> Maybe not in our plan now unless it is a major request because it is not relevant to the main logic of this project and bit tedious. However, if you are interested in the implementation, we are willing to share any details and answer any questions! We can discuss it here or on discord.

Hi there, I would love to use the xlang-code-interpreter but need to install additional non-public custom Python libraries into it, so that my custom agent can use them. I have tried to achieve this by myself, but have not succeeded so far (and with my rather limited knowledge of Docker, I am not sure if it is possible at all with just the image). 

Any chance you could release or share the repo? Or do you have any suggestions on how I could achieve my goal of installing additional non-public custom Python libraries into it? Any help would be much appreciated. Many thanks in advance, and kind regards.
